In [ ]:
# Data Processing 
# Data Loading & Structure Analysis
# Import necessary libraries #Make sure pandas is installed in environment
import pandas as pd

# Load the datasets
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')
submission = pd.read_csv('../data/submission.csv')

In [2]:
# Quick peek at each dataset
print("Train Dataset Preview:")
display(train.head())

print("\nTest Dataset Preview:")
display(test.head())

print("\nSubmission File Preview:")
display(submission.head())

Train Dataset Preview:

,Unnamed: 0,id,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,0,261358,Y. Sylla,Youssuf Sylla,ST,58,76,525000.0,952.712115,18,...,43,13,19,17,7,6,8,10,7,NaN
1,1,252435,J. Austerfield,Josh Austerfield,"CM, CDM",55,75,350000.0,902.232819,19,...,48,40,48,45,14,8,5,14,11,NaN
2,2,248723,C. Malley,Connor Malley,"CAM, CM",53,66,230000.0,2873.818374,21,...,52,26,23,31,14,8,13,9,6,NaN
3,3,251157,Lee Gwang Yeon,이광연 Gwang Yeon Lee,GK,60,71,475000.0,678.608124,21,...,26,8,14,12,60,60,54,63,61,23.0
4,4,205393,J. Baldwin,Jack Baldwin,CB,63,65,475000.0,1911.674228,28,...,67,62,63,62,11,12,6,11,14,NaN

Test Dataset Preview:

,Unnamed: 0,id,short_name,long_name,player_positions,overall,potential,wage_eur,age,dob,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,0,233938,D. Kasumu,David Ayomide Kasumu,CM,63,73,1927.187704,21,1999-10-05,...,61,63,61,58,12,10,11,14,13,NaN
1,1,261545,B. Villacis,Brando Enrique Villacis Vega,CB,57,66,482.073719,22,1998-09-26,...,39,54,56,54,15,11,10,8,7,NaN
2,2,260387,J. Assi,Jean-Aniel Assi,"ST, RW",52,75,471.659254,16,2004-08-12,...,45,22,23,28,11,13,6,7,13,NaN
3,3,241960,T. Stavitski,Timo Stavitski,RW,63,71,946.789206,21,1999-07-17,...,53,17,35,31,14,12,12,9,10,NaN
4,4,234645,N. McGinley,Nathan McGinley,"LB, CB",63,64,954.732171,24,1996-09-15,...,56,61,62,60,13,14,12,9,6,NaN

Submission File Preview:

   Unnamed: 0   value_eur
0           0  943.108068
1           1  266.597577
2           2  936.688239
3           3  804.858915
4           4  730.894054

In [3]:
#Structure Analysis
# 1. Dataset Dimensions
print(f"Train dataset: {train.shape[0]} rows × {train.shape[1]} columns")
print(f"Test dataset: {test.shape[0]} rows × {test.shape[1]} columns")

# 2. Data types
print("\nData Types in Train dataset:")
print(train.dtypes)

Train dataset: 15391 rows × 76 columns
Test dataset: 3848 rows × 75 columns

Data Types in Train dataset:
Unnamed: 0                   int64
id                           int64
short_name                  object
long_name                   object
player_positions            object
                            ...
goalkeeping_handling         int64
goalkeeping_kicking          int64
goalkeeping_positioning      int64
goalkeeping_reflexes         int64
goalkeeping_speed          float64
Length: 76, dtype: object

In [5]:
#Missing Values
print("\nMissing Values in Train dataset:")
missing_counts = train.isnull().sum()
missing_percentage = (missing_counts / len(train)) * 100

#Table of column(features) with missing variables from highest to lowest
missing_df = pd.DataFrame({'Missing Values': missing_counts, 'Percentage': missing_percentage})
display(missing_df[missing_df['Missing Values'] > 0].sort_values('Missing Values', ascending=False))

Missing Values in Train dataset:

                           Missing Values  Percentage
nation_jersey_number                14786   96.069131
nation_position                     14786   96.069131
club_loaned_from                    14515   94.308362
player_tags                         14231   92.463128
goalkeeping_speed                   13662   88.766162
player_traits                        7936   51.562602
pace                                 1729   11.233838
passing                              1729   11.233838
dribbling                            1729   11.233838
defending                            1729   11.233838
physic                               1729   11.233838
shooting                             1729   11.233838
release_clause_eur                    934    6.068482
club_joined                           925    6.010006
value_eur                              58    0.376844
club_position                          49    0.318368
league_level                           49    0.318368
league_name                            49    0.318368
club_name                              49    0.318368
club_team_id                           49    0.318368
wage_eur                               49    0.318368
club_jersey_number                     49    0.318368
club_contract_valid_until              49    0.318368

In [7]:
#Types of features
categorical_features = train.select_dtypes(include=['object']).columns.tolist()
numerical_features = train.select_dtypes(include=['number']).columns.tolist()

print(f"\nNumber of Categorical Features: {len(categorical_features)}")
print(f"Categorical Features: {categorical_features}")

print(f"\nNumber of Numerical Features: {len(numerical_features)}")
print(f"Numerical Features: {numerical_features}")

Number of Categorical Features: 16
Categorical Features: ['short_name', 'long_name', 'player_positions', 'dob', 'club_name', 'league_name', 'club_position', 'club_loaned_from', 'club_joined', 'nationality_name', 'nation_position', 'preferred_foot', 'work_rate', 'body_type', 'player_tags', 'player_traits']

Number of Numerical Features: 60
Numerical Features: ['Unnamed: 0', 'id', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'height_cm', 'weight_kg', 'club_team_id', 'league_level', 'club_jersey_number', 'club_contract_valid_until', 'nationality_id', 'nation_jersey_number', 'weak_foot', 'skill_moves', 'international_reputation', 'release_clause_eur', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']